const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const { normalizeVersionTag, syncReleaseVersion } = require("./sync-release-version.cjs");

function writeFixture(root) {
  fs.mkdirSync(path.join(root, "src-tauri"), { recursive: true });

  fs.writeFileSync(
    path.join(root, "package.json"),
    JSON.stringify(
      {
        name: "studio-display-brightness-controller",
        version: "0.1.0",
      },
      null,
      2,
    ) + "\n",
  );

  fs.writeFileSync(
    path.join(root, "package-lock.json"),
    JSON.stringify(
      {
        name: "studio-display-brightness-controller",
        version: "0.1.0",
        lockfileVersion: 3,
        packages: {
          "": {
            name: "studio-display-brightness-controller",
            version: "0.1.0",
          },
        },
      },
      null,
      2,
    ) + "\n",
  );

  fs.writeFileSync(
    path.join(root, "src-tauri", "Cargo.toml"),
    [
      "[package]",
      'name = "studio-display-brightness-controller"',
      'version = "0.1.0"',
      'description = "Apple Studio Display brightness controller for Windows."',
      "",
      "[dependencies]",
      'serde = { version = "1", features = ["derive"] }',
      "",
    ].join("\n"),
  );

  fs.writeFileSync(
    path.join(root, "src-tauri", "Cargo.lock"),
    [
      "# This file is automatically @generated by Cargo.",
      "version = 4",
      "",
      "[[package]]",
      'name = "serde"',
      'version = "1.0.0"',
      "",
      "[[package]]",
      'name = "studio-display-brightness-controller"',
      'version = "0.1.0"',
      "",
    ].join("\n"),
  );

  fs.writeFileSync(
    path.join(root, "src-tauri", "tauri.conf.json"),
    JSON.stringify(
      {
        productName: "StudioDisplayBrightnessController",
        version: "0.1.0",
        app: {
          windows: [
            {
              title: "Studio Display Brightness",
              width: 560,
              height: 420,
            },
          ],
        },
      },
      null,
      2,
    ) + "\n",
  );

  fs.writeFileSync(
    path.join(root, "index.html"),
    '<!doctype html>\n<html><head><title>Studio Display Brightness Controller</title></head><body></body></html>\n',
  );
}

function withFixture(callback) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "sdbc-release-version-"));

  try {
    writeFixture(root);
    callback(root);
  } finally {
    fs.rmSync(root, { force: true, recursive: true });
  }
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

assert.equal(normalizeVersionTag("v1.2.3"), "1.2.3");
assert.throws(() => normalizeVersionTag("1.2.3"), /Expected version tag/);
assert.throws(() => normalizeVersionTag("v1.2"), /Expected version tag/);
assert.throws(() => normalizeVersionTag("v1.2.3-beta.1"), /Expected version tag/);

withFixture((root) => {
  const result = syncReleaseVersion(root, "v1.2.3");

  assert.deepEqual(result, {
    title: "Studio Display Brightness v1.2.3",
    version: "1.2.3",
  });

  assert.equal(readJson(path.join(root, "package.json")).version, "1.2.3");
  assert.equal(readJson(path.join(root, "package-lock.json")).version, "1.2.3");
  assert.equal(readJson(path.join(root, "package-lock.json")).packages[""].version, "1.2.3");

  const cargoToml = fs.readFileSync(path.join(root, "src-tauri", "Cargo.toml"), "utf8");
  assert.match(cargoToml, /^version = "1\.2\.3"$/m);
  assert.match(cargoToml, /serde = \{ version = "1"/);

  const cargoLock = fs.readFileSync(path.join(root, "src-tauri", "Cargo.lock"), "utf8");
  assert.match(cargoLock, /name = "serde"\nversion = "1\.0\.0"/);
  assert.match(cargoLock, /name = "studio-display-brightness-controller"\nversion = "1\.2\.3"/);

  const tauriConfig = readJson(path.join(root, "src-tauri", "tauri.conf.json"));
  assert.equal(tauriConfig.version, "1.2.3");
  assert.equal(tauriConfig.app.windows[0].title, "Studio Display Brightness v1.2.3");

  const html = fs.readFileSync(path.join(root, "index.html"), "utf8");
  assert.match(html, /<title>Studio Display Brightness v1\.2\.3<\/title>/);
});
